version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "coder-tavi"
    commit-message:
      prefix: "chore:"
    ignore:
      - dependency-name: "node-fetch"
        versions: ["3.x"]
